name: Tests

on:
  pull_request:
    branches:
      - release
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        database: ["sqlite"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.5.1

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m poetry install

      - name: Test with tox
        id: test-with-tox
        run: |
          ./.venv/bin/tox
        env:
          DATABASE: ${{ matrix.database }}

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        database: ["postgres"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.5.1

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m poetry install

      - name: Test with tox
        id: test-with-tox
        run: |
          ./.venv/bin/tox
        env:
          DB_NAME: postgres
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DATABASE: ${{ matrix.database }}


  test-mysql:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        database: ["mysql"]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: mysql
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.5.1

      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        id: install-dependencies
        run: |
          python -m poetry install

      - name: Test with tox
        id: test-with-tox
        run: |
          ./.venv/bin/tox
        env:
          DB_NAME: test
          DB_USER: root
          DB_PASSWORD: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DATABASE: ${{ matrix.database }}
